services:
  redis:
    container_name: redis
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - puffer_redis:/data
    networks:
      - puffer_network

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - puffer_db:/var/lib/postgresql/data
    networks:
      - puffer_network

networks:
  puffer_network:
    external: true

volumes:
  puffer_redis:
    external: true
  puffer_db:
    external: true
