services:
  redis:
    container_name: redis
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - puffer_redis:/data
    networks:
      - puffer_network

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - puffer_db:/var/lib/postgresql/data
    networks:
      - puffer_network

  # rtmd:
  #   container_name: rtmd
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       APP_NAME: rtmd
  #   env_file:
  #     - .env.deploy
  #   restart: always
  #   networks:
  #     - puffer_network
  #   depends_on:
  #     timescaledb:
  #       condition: service_started
  #     redis:
  #       condition: service_started

  # backfiller:
  #   container_name: backfiller
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       APP_NAME: backfiller
  #   env_file:
  #     - .env.deploy
  #   restart: always
  #   networks:
  #     - puffer_network
  #   depends_on:
  #     timescaledb:
  #       condition: service_started
  #     redis:
  #       condition: service_started

  # front:
  #   container_name: front
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       APP_NAME: front
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - .env.deploy
  #   restart: always
  #   networks:
  #     - puffer_network
  #   depends_on:
  #     timescaledb:
  #       condition: service_started
  #     redis:
  #       condition: service_started

networks:
  puffer_network:
    external: true

volumes:
  puffer_redis:
    external: true
  puffer_db:
    external: true
