// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type PufferConversionRate struct {
	Chain            string    `json:"chain"`
	BlockNumber      int64     `json:"block_number"`
	BlockTimestampMs int64     `json:"block_timestamp_ms"`
	TotalAsset       string    `json:"total_asset"`
	TotalSupply      string    `json:"total_supply"`
	ConversionRate   string    `json:"conversion_rate"`
	CreatedAt        time.Time `json:"created_at"`
}
