// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetChains(ctx context.Context) ([]string, error)
	GetHistoricalPufferRates(ctx context.Context, arg GetHistoricalPufferRatesParams) ([]PufferConversionRate, error)
	GetLatestPufferRate(ctx context.Context, chain string) (PufferConversionRate, error)
	InsertPufferRate(ctx context.Context, arg InsertPufferRateParams) (PufferConversionRate, error)
}

var _ Querier = (*Queries)(nil)
